service: image-resizer

frameworkVersion: '3'

provider:
  name: aws
  stage: prod
  runtime: nodejs14.x
  region: eu-central-1

  endpointType: regional
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::pulfy-media/*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:GetObjects"
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::pulfy-media-private/*"
  stackTags:
    environment: prod
    application: ${self:service}
    product: ImageResizer

package:
  individually: true
  excludeDevDependencies: true

functions:
  resizeImage:
    handler: handler.resize
    events:
      - s3:
          bucket: pulfy-media-private
          event: s3:ObjectCreated:*
          existing: true
